DROP DATABASE IF EXISTS topSongsDB;
CREATE DATABASE topSongsDB;
USE topSongsDB;
CREATE TABLE top1000Songs(
    id  INT NOT NULL,
    ARTIST_NAME VARCHAR(100) NULL,
    song_title VARCHAR(100) NULL,
    year VARCHAR(100) NULL,
    COL5 VARCHAR(100) NULL,
    COL6 VARCHAR(100) NULL,
    COL7 VARCHAR(100) NULL,
    COL8 VARCHAR(100) NULL,
    COL9 VARCHAR(100) NULL
)